// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuoK9xJrcfnoP--vhKjCjZhk5xpnzehNY',
    appId: '1:758992724359:web:89af2ff4f65f90248d3322',
    messagingSenderId: '758992724359',
    projectId: 'news-menia-ebbbd',
    authDomain: 'news-menia-ebbbd.firebaseapp.com',
    storageBucket: 'news-menia-ebbbd.appspot.com',
    measurementId: 'G-H272CE4X8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_EeiT0lVy7_JYimebi-83xc0Ny0gZ6Hw',
    appId: '1:758992724359:android:6ae544b956c33d8b8d3322',
    messagingSenderId: '758992724359',
    projectId: 'news-menia-ebbbd',
    storageBucket: 'news-menia-ebbbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv-_nxiYVqlhDbL4cnBV_xHMFi0MMMqAE',
    appId: '1:758992724359:ios:9361491264dcd06a8d3322',
    messagingSenderId: '758992724359',
    projectId: 'news-menia-ebbbd',
    storageBucket: 'news-menia-ebbbd.appspot.com',
    iosBundleId: 'com.example.newsMenia',
  );
}
